<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPk83K0p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPk83K0p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPk83K0p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPk83K0p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPk83K0p\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pk83K0p',
    'container.build_id' => '3582015f',
    'container.build_time' => 1740487888,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPk83K0p');
