<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWPHNx4P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWPHNx4P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWPHNx4P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWPHNx4P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWPHNx4P\App_KernelDevDebugContainer([
    'container.build_hash' => 'WPHNx4P',
    'container.build_id' => 'f948807b',
    'container.build_time' => 1740557927,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWPHNx4P');
