<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDzhvrpe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDzhvrpe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDzhvrpe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDzhvrpe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDzhvrpe\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dzhvrpe',
    'container.build_id' => 'bf3e06cb',
    'container.build_time' => 1740493447,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDzhvrpe');
